#!/bin/bash
./CoFIM_1 -data ../Pokec_SNAP/IPA/graph.txt -com ../Pokec_SNAP/Pokec_com.txt -k 50 -gamma 3
./CoFIM_1 -data ../Pokec_SNAP/IPA/graph.txt -com ../Pokec_SNAP/Pokec_com.txt -k 50 -gamma 6
./CoFIM_1 -data ../Pokec_SNAP/IPA/graph.txt -com ../Pokec_SNAP/Pokec_com.txt -k 50 -gamma 10
./CoFIM_1 -data ../Pokec_SNAP/IPA/graph.txt -com ../Pokec_SNAP/Pokec_com.txt -k 50 -gamma 20
./CoFIM_1 -data ../Pokec_SNAP/IPA/graph.txt -com ../Pokec_SNAP/Pokec_com.txt -k 50 -gamma 50
./CoFIM_1 -data ../Pokec_SNAP/IPA/graph.txt -com ../Pokec_SNAP/Pokec_com.txt -k 50 -gamma 100
./CoFIM_1 -data ../Pokec_SNAP/IPA/graph.txt -com ../Pokec_SNAP/Pokec_com.txt -k 50 -gamma 200
./CoFIM_1 -data ../Pokec_SNAP/IPA/graph.txt -com ../Pokec_SNAP/Pokec_com.txt -k 50 -gamma 1000
./CoFIM_1 -data ../LiveJournal_SNAP/IPA/graph.txt -com ../LiveJournal_SNAP/LiveJournal_com.txt -k 50 -gamma 0
./CoFIM_1 -data ../LiveJournal_SNAP/IPA/graph.txt -com ../LiveJournal_SNAP/LiveJournal_com.txt -k 50 -gamma 1
./CoFIM_1 -data ../LiveJournal_SNAP/IPA/graph.txt -com ../LiveJournal_SNAP/LiveJournal_com.txt -k 50 -gamma 2
./CoFIM_1 -data ../LiveJournal_SNAP/IPA/graph.txt -com ../LiveJournal_SNAP/LiveJournal_com.txt -k 50 -gamma 3
./CoFIM_1 -data ../LiveJournal_SNAP/IPA/graph.txt -com ../LiveJournal_SNAP/LiveJournal_com.txt -k 50 -gamma 6
./CoFIM_1 -data ../LiveJournal_SNAP/IPA/graph.txt -com ../LiveJournal_SNAP/LiveJournal_com.txt -k 50 -gamma 10
./CoFIM_1 -data ../LiveJournal_SNAP/IPA/graph.txt -com ../LiveJournal_SNAP/LiveJournal_com.txt -k 50 -gamma 20
./CoFIM_1 -data ../LiveJournal_SNAP/IPA/graph.txt -com ../LiveJournal_SNAP/LiveJournal_com.txt -k 50 -gamma 50
./CoFIM_1 -data ../LiveJournal_SNAP/IPA/graph.txt -com ../LiveJournal_SNAP/LiveJournal_com.txt -k 50 -gamma 100
./CoFIM_1 -data ../LiveJournal_SNAP/IPA/graph.txt -com ../LiveJournal_SNAP/LiveJournal_com.txt -k 50 -gamma 200
./CoFIM_1 -data ../LiveJournal_SNAP/IPA/graph.txt -com ../LiveJournal_SNAP/LiveJournal_com.txt -k 50 -gamma 1000
./CoFIM_1 -data ../Orkut_SNAP/IPA/graph.txt -com ../Orkut_SNAP/Orkut_com.txt -k 50 -gamma 0
./CoFIM_1 -data ../Orkut_SNAP/IPA/graph.txt -com ../Orkut_SNAP/Orkut_com.txt -k 50 -gamma 1
./CoFIM_1 -data ../Orkut_SNAP/IPA/graph.txt -com ../Orkut_SNAP/Orkut_com.txt -k 50 -gamma 2
./CoFIM_1 -data ../Orkut_SNAP/IPA/graph.txt -com ../Orkut_SNAP/Orkut_com.txt -k 50 -gamma 3
./CoFIM_1 -data ../Orkut_SNAP/IPA/graph.txt -com ../Orkut_SNAP/Orkut_com.txt -k 50 -gamma 6
./CoFIM_1 -data ../Orkut_SNAP/IPA/graph.txt -com ../Orkut_SNAP/Orkut_com.txt -k 50 -gamma 10
./CoFIM_1 -data ../Orkut_SNAP/IPA/graph.txt -com ../Orkut_SNAP/Orkut_com.txt -k 50 -gamma 20
./CoFIM_1 -data ../Orkut_SNAP/IPA/graph.txt -com ../Orkut_SNAP/Orkut_com.txt -k 50 -gamma 50
./CoFIM_1 -data ../Orkut_SNAP/IPA/graph.txt -com ../Orkut_SNAP/Orkut_com.txt -k 50 -gamma 100
./CoFIM_1 -data ../Orkut_SNAP/IPA/graph.txt -com ../Orkut_SNAP/Orkut_com.txt -k 50 -gamma 200
./CoFIM_1 -data ../Orkut_SNAP/IPA/graph.txt -com ../Orkut_SNAP/Orkut_com.txt -k 50 -gamma 1000